# config/norm_config.py

NUM_AS_WORDS = {
  "zero": "0",
  "one": "1",
  "two": "2",
  "three": "3",
  "four": "4",
  "five": "5",
  "six": "6",
  "seven": "7",
  "eight": "8",
  "nine": "9",
  "ten": "10",
  "eleven": "11",
  "twelve": "12",
  "thirteen": "13",
  "fourteen": "14",
  "fifteen": "15",
  "sixteen": "16",
  "seventeen": "17",
  "eighteen": "18",
  "nineteen": "19",
  "twenty": "20",
  "twenty one": "21",
  "twenty two": "22",
  "twenty three": "23",
  "twenty four": "24",
  "twenty five": "25",
  "twenty six": "26",
  "twenty seven": "27",
  "twenty eight": "28",
  "twenty nine": "29",
  "thirty": "30",
  "thirty one": "31",
  "thirty two": "32",
  "thirty three": "33",
  "thirty four": "34",
  "thirty five": "35",
  "thirty six": "36",
  "thirty seven": "37",
  "thirty eight": "38",
  "thirty nine": "39",
  "forty": "40",
  "forty one": "41",
  "forty two": "42",
  "forty three": "43",
  "forty four": "44",
  "forty five": "45",
  "forty six": "46",
  "forty seven": "47",
  "forty eight": "48",
  "forty nine": "49",
  "fifty": "50",
  "fifty one": "51",
  "fifty two": "52",
  "fifty three": "53",
  "fifty four": "54",
  "fifty five": "55",
  "fifty six": "56",
  "fifty seven": "57",
  "fifty eight": "58",
  "fifty nine": "59",
  "sixty": "60",
  "sixty one": "61",
  "sixty two": "62",
  "sixty three": "63",
  "sixty four": "64",
  "sixty five": "65",
  "sixty six": "66",
  "sixty seven": "67",
  "sixty eight": "68",
  "sixty nine": "69",
  "seventy": "70",
  "seventy one": "71",
  "seventy two": "72",
  "seventy three": "73",
  "seventy four": "74",
  "seventy five": "75",
  "seventy six": "76",
  "seventy seven": "77",
  "seventy eight": "78",
  "seventy nine": "79",
  "eighty": "80",
  "eighty one": "81",
  "eighty two": "82",
  "eighty three": "83",
  "eighty four": "84",
  "eighty five": "85",
  "eighty six": "86",
  "eighty seven": "87",
  "eighty eight": "88",
  "eighty nine": "89",
  "ninety": "90",
  "ninety one": "91",
  "ninety two": "92",
  "ninety three": "93",
  "ninety four": "94",
  "ninety five": "95",
  "ninety six": "96",
  "ninety seven": "97",
  "ninety eight": "98",
  "ninety nine": "99",
  "hundred": "100",
  "one hundred": "100",
  "one hundred one": "101",
  "one hundred two": "102",
  "one hundred three": "103",
  "one hundred four": "104",
  "one hundred five": "105",
  "one hundred six": "106",
  "one hundred seven": "107",
  "one hundred eight": "108",
  "one hundred nine": "109",
  "one hundred ten": "110",
  "one hundred eleven": "111",
  "one hundred twelve": "112",
  "one hundred thirteen": "113",
  "one hundred fourteen": "114",
  "one hundred fifteen": "115",
  "one hundred sixteen": "116",
  "one hundred seventeen": "117",
  "one hundred eighteen": "118",
  "one hundred nineteen": "119",
  "one hundred twenty": "120",
  "one hundred twenty one": "121",
  "one hundred twenty two": "122",
  "one hundred twenty three": "123",
  "one hundred twenty four": "124",
  "one hundred twenty five": "125",
  "one hundred twenty six": "126",
  "one hundred twenty seven": "127",
  "one hundred twenty eight": "128",
  "one hundred twenty nine": "129",
  "one hundred thirty": "130",
  "one hundred thirty one": "131",
  "one hundred thirty two": "132",
  "one hundred thirty three": "133",
  "one hundred thirty four": "134",
  "one hundred thirty five": "135",
  "one hundred thirty six": "136",
  "one hundred thirty seven": "137",
  "one hundred thirty eight": "138",
  "one hundred thirty nine": "139",
  "one hundred forty": "140",
  "one hundred forty one": "141",
  "one hundred forty two": "142",
  "one hundred forty three": "143",
  "one hundred forty four": "144",
  "one hundred forty five": "145",
  "one hundred forty six": "146",
  "one hundred forty seven": "147",
  "one hundred forty eight": "148",
  "one hundred forty nine": "149",
  "one hundred fifty": "150",
  "one hundred fifty one": "151",
  "one hundred fifty two": "152",
  "one hundred fifty three": "153",
  "one hundred fifty four": "154",
  "one hundred fifty five": "155",
  "one hundred fifty six": "156",
  "one hundred fifty seven": "157",
  "one hundred fifty eight": "158",
  "one hundred fifty nine": "159",
  "one hundred sixty": "160",
  "one hundred sixty one": "161",
  "one hundred sixty two": "162",
  "one hundred sixty three": "163",
  "one hundred sixty four": "164",
  "one hundred sixty five": "165",
  "one hundred sixty six": "166",
  "one hundred sixty seven": "167",
  "one hundred sixty eight": "168",
  "one hundred sixty nine": "169",
  "one hundred seventy": "170",
  "one hundred seventy one": "171",
  "one hundred seventy two": "172",
  "one hundred seventy three": "173",
  "one hundred seventy four": "174",
  "one hundred seventy five": "175",
  "one hundred seventy six": "176",
  "one hundred seventy seven": "177",
  "one hundred seventy eight": "178",
  "one hundred seventy nine": "179",
  "one hundred eighty": "180",
  "one hundred eighty one": "181",
  "one hundred eighty two": "182",
  "one hundred eighty three": "183",
  "one hundred eighty four": "184",
  "one hundred eighty five": "185",
  "one hundred eighty six": "186",
  "one hundred eighty seven": "187",
  "one hundred eighty eight": "188",
  "one hundred eighty nine": "189",
  "one hundred ninety": "190",
  "one hundred ninety one": "191",
  "one hundred ninety two": "192",
  "one hundred ninety three": "193",
  "one hundred ninety four": "194",
  "one hundred ninety five": "195",
  "one hundred ninety six": "196",
  "one hundred ninety seven": "197",
  "one hundred ninety eight": "198",
  "one hundred ninety nine": "199",
  "two hundred": "200",
  "two hundred one": "201",
  "two hundred two": "202",
  "two hundred three": "203",
  "two hundred four": "204",
  "two hundred five": "205",
  "two hundred six": "206",
  "two hundred seven": "207",
  "two hundred eight": "208",
  "two hundred nine": "209",
  "two hundred ten": "210",
  "two hundred eleven": "211",
  "two hundred twelve": "212",
  "two hundred thirteen": "213",
  "two hundred fourteen": "214",
  "two hundred fifteen": "215",
  "two hundred sixteen": "216",
  "two hundred seventeen": "217",
  "two hundred eighteen": "218",
  "two hundred nineteen": "219",
  "two hundred twenty": "220",
  "two hundred twenty one": "221",
  "two hundred twenty two": "222",
  "two hundred twenty three": "223",
  "two hundred twenty four": "224",
  "two hundred twenty five": "225",
  "two hundred twenty six": "226",
  "two hundred twenty seven": "227",
  "two hundred twenty eight": "228",
  "two hundred twenty nine": "229",
  "two hundred thirty": "230",
  "two hundred thirty one": "231",
  "two hundred thirty two": "232",
  "two hundred thirty three": "233",
  "two hundred thirty four": "234",
  "two hundred thirty five": "235",
  "two hundred thirty six": "236",
  "two hundred thirty seven": "237",
  "two hundred thirty eight": "238",
  "two hundred thirty nine": "239",
  "two hundred forty": "240",
  "two hundred forty one": "241",
  "two hundred forty two": "242",
  "two hundred forty three": "243",
  "two hundred forty four": "244",
  "two hundred forty five": "245",
  "two hundred forty six": "246",
  "two hundred forty seven": "247",
  "two hundred forty eight": "248",
  "two hundred forty nine": "249",
  "two hundred fifty": "250",
  "two hundred fifty one": "251",
  "two hundred fifty two": "252",
  "two hundred fifty three": "253",
  "two hundred fifty four": "254",
  "two hundred fifty five": "255",
  "two hundred fifty six": "256",
  "two hundred fifty seven": "257",
  "two hundred fifty eight": "258",
  "two hundred fifty nine": "259",
  "two hundred sixty": "260",
  "two hundred sixty one": "261",
  "two hundred sixty two": "262",
  "two hundred sixty three": "263",
  "two hundred sixty four": "264",
  "two hundred sixty five": "265",
  "two hundred sixty six": "266",
  "two hundred sixty seven": "267",
  "two hundred sixty eight": "268",
  "two hundred sixty nine": "269",
  "two hundred seventy": "270",
  "two hundred seventy one": "271",
  "two hundred seventy two": "272",
  "two hundred seventy three": "273",
  "two hundred seventy four": "274",
  "two hundred seventy five": "275",
  "two hundred seventy six": "276",
  "two hundred seventy seven": "277",
  "two hundred seventy eight": "278",
  "two hundred seventy nine": "279",
  "two hundred eighty": "280",
  "two hundred eighty one": "281",
  "two hundred eighty two": "282",
  "two hundred eighty three": "283",
  "two hundred eighty four": "284",
  "two hundred eighty five": "285",
  "two hundred eighty six": "286",
  "two hundred eighty seven": "287",
  "two hundred eighty eight": "288",
  "two hundred eighty nine": "289",
  "two hundred ninety": "290",
  "two hundred ninety one": "291",
  "two hundred ninety two": "292",
  "two hundred ninety three": "293",
  "two hundred ninety four": "294",
  "two hundred ninety five": "295",
  "two hundred ninety six": "296",
  "two hundred ninety seven": "297",
  "two hundred ninety eight": "298",
  "two hundred ninety nine": "299",
  "three hundred": "300",
  "three hundred one": "301",
  "three hundred two": "302",
  "three hundred three": "303",
  "three hundred four": "304",
  "three hundred five": "305",
  "three hundred six": "306",
  "three hundred seven": "307",
  "three hundred eight": "308",
  "three hundred nine": "309",
  "three hundred ten": "310",
  "three hundred eleven": "311",
  "three hundred twelve": "312",
  "three hundred thirteen": "313",
  "three hundred fourteen": "314",
  "three hundred fifteen": "315",
  "three hundred sixteen": "316",
  "three hundred seventeen": "317",
  "three hundred eighteen": "318",
  "three hundred nineteen": "319",
  "three hundred twenty": "320",
  "three hundred twenty one": "321",
  "three hundred twenty two": "322",
  "three hundred twenty three": "323",
  "three hundred twenty four": "324",
  "three hundred twenty five": "325",
  "three hundred twenty six": "326",
  "three hundred twenty seven": "327",
  "three hundred twenty eight": "328",
  "three hundred twenty nine": "329",
  "three hundred thirty": "330",
  "three hundred thirty one": "331",
  "three hundred thirty two": "332",
  "three hundred thirty three": "333",
  "three hundred thirty four": "334",
  "three hundred thirty five": "335",
  "three hundred thirty six": "336",
  "three hundred thirty seven": "337",
  "three hundred thirty eight": "338",
  "three hundred thirty nine": "339",
  "three hundred forty": "340",
  "three hundred forty one": "341",
  "three hundred forty two": "342",
  "three hundred forty three": "343",
  "three hundred forty four": "344",
  "three hundred forty five": "345",
  "three hundred forty six": "346",
  "three hundred forty seven": "347",
  "three hundred forty eight": "348",
  "three hundred forty nine": "349",
  "three hundred fifty": "350",
  "three hundred fifty one": "351",
  "three hundred fifty two": "352",
  "three hundred fifty three": "353",
  "three hundred fifty four": "354",
  "three hundred fifty five": "355",
  "three hundred fifty six": "356",
  "three hundred fifty seven": "357",
  "three hundred fifty eight": "358",
  "three hundred fifty nine": "359",
  "three hundred sixty": "360",
  "three hundred sixty one": "361",
  "three hundred sixty two": "362",
  "three hundred sixty three": "363",
  "three hundred sixty four": "364",
  "three hundred sixty five": "365",
  "three hundred sixty six": "366",
  "three hundred sixty seven": "367",
  "three hundred sixty eight": "368",
  "three hundred sixty nine": "369",
  "three hundred seventy": "370",
  "three hundred seventy one": "371",
  "three hundred seventy two": "372",
  "three hundred seventy three": "373",
  "three hundred seventy four": "374",
  "three hundred seventy five": "375",
  "three hundred seventy six": "376",
  "three hundred seventy seven": "377",
  "three hundred seventy eight": "378",
  "three hundred seventy nine": "379",
  "three hundred eighty": "380",
  "three hundred eighty one": "381",
  "three hundred eighty two": "382",
  "three hundred eighty three": "383",
  "three hundred eighty four": "384",
  "three hundred eighty five": "385",
  "three hundred eighty six": "386",
  "three hundred eighty seven": "387",
  "three hundred eighty eight": "388",
  "three hundred eighty nine": "389",
  "three hundred ninety": "390",
  "three hundred ninety one": "391",
  "three hundred ninety two": "392",
  "three hundred ninety three": "393",
  "three hundred ninety four": "394",
  "three hundred ninety five": "395",
  "three hundred ninety six": "396",
  "three hundred ninety seven": "397",
  "three hundred ninety eight": "398",
  "three hundred ninety nine": "399",
  "four hundred": "400",
  "four hundred one": "401",
  "four hundred two": "402",
  "four hundred three": "403",
  "four hundred four": "404",
  "four hundred five": "405",
  "four hundred six": "406",
  "four hundred seven": "407",
  "four hundred eight": "408",
  "four hundred nine": "409",
  "four hundred ten": "410",
  "four hundred eleven": "411",
  "four hundred twelve": "412",
  "four hundred thirteen": "413",
  "four hundred fourteen": "414",
  "four hundred fifteen": "415",
  "four hundred sixteen": "416",
  "four hundred seventeen": "417",
  "four hundred eighteen": "418",
  "four hundred nineteen": "419",
  "four hundred twenty": "420",
  "four hundred twenty one": "421",
  "four hundred twenty two": "422",
  "four hundred twenty three": "423",
  "four hundred twenty four": "424",
  "four hundred twenty five": "425",
  "four hundred twenty six": "426",
  "four hundred twenty seven": "427",
  "four hundred twenty eight": "428",
  "four hundred twenty nine": "429",
  "four hundred thirty": "430",
  "four hundred thirty one": "431",
  "four hundred thirty two": "432",
  "four hundred thirty three": "433",
  "four hundred thirty four": "434",
  "four hundred thirty five": "435",
  "four hundred thirty six": "436",
  "four hundred thirty seven": "437",
  "four hundred thirty eight": "438",
  "four hundred thirty nine": "439",
  "four hundred forty": "440",
  "four hundred forty one": "441",
  "four hundred forty two": "442",
  "four hundred forty three": "443",
  "four hundred forty four": "444",
  "four hundred forty five": "445",
  "four hundred forty six": "446",
  "four hundred forty seven": "447",
  "four hundred forty eight": "448",
  "four hundred forty nine": "449",
  "four hundred fifty": "450",
  "four hundred fifty one": "451",
  "four hundred fifty two": "452",
  "four hundred fifty three": "453",
  "four hundred fifty four": "454",
  "four hundred fifty five": "455",
  "four hundred fifty six": "456",
  "four hundred fifty seven": "457",
  "four hundred fifty eight": "458",
  "four hundred fifty nine": "459",
  "four hundred sixty": "460",
  "four hundred sixty one": "461",
  "four hundred sixty two": "462",
  "four hundred sixty three": "463",
  "four hundred sixty four": "464",
  "four hundred sixty five": "465",
  "four hundred sixty six": "466",
  "four hundred sixty seven": "467",
  "four hundred sixty eight": "468",
  "four hundred sixty nine": "469",
  "four hundred seventy": "470",
  "four hundred seventy one": "471",
  "four hundred seventy two": "472",
  "four hundred seventy three": "473",
  "four hundred seventy four": "474",
  "four hundred seventy five": "475",
  "four hundred seventy six": "476",
  "four hundred seventy seven": "477",
  "four hundred seventy eight": "478",
  "four hundred seventy nine": "479",
  "four hundred eighty": "480",
  "four hundred eighty one": "481",
  "four hundred eighty two": "482",
  "four hundred eighty three": "483",
  "four hundred eighty four": "484",
  "four hundred eighty five": "485",
  "four hundred eighty six": "486",
  "four hundred eighty seven": "487",
  "four hundred eighty eight": "488",
  "four hundred eighty nine": "489",
  "four hundred ninety": "490",
  "four hundred ninety one": "491",
  "four hundred ninety two": "492",
  "four hundred ninety three": "493",
  "four hundred ninety four": "494",
  "four hundred ninety five": "495",
  "four hundred ninety six": "496",
  "four hundred ninety seven": "497",
  "four hundred ninety eight": "498",
  "four hundred ninety nine": "499",
  "five hundred": "500",
  "five hundred one": "501",
  "five hundred two": "502",
  "five hundred three": "503",
  "five hundred four": "504",
  "five hundred five": "505",
  "five hundred six": "506",
  "five hundred seven": "507",
  "five hundred eight": "508",
  "five hundred nine": "509",
  "five hundred ten": "510",
  "five hundred eleven": "511",
  "five hundred twelve": "512",
  "five hundred thirteen": "513",
  "five hundred fourteen": "514",
  "five hundred fifteen": "515",
  "five hundred sixteen": "516",
  "five hundred seventeen": "517",
  "five hundred eighteen": "518",
  "five hundred nineteen": "519",
  "five hundred twenty": "520",
  "five hundred twenty one": "521",
  "five hundred twenty two": "522",
  "five hundred twenty three": "523",
  "five hundred twenty four": "524",
  "five hundred twenty five": "525",
  "five hundred twenty six": "526",
  "five hundred twenty seven": "527",
  "five hundred twenty eight": "528",
  "five hundred twenty nine": "529",
  "five hundred thirty": "530",
  "five hundred thirty one": "531",
  "five hundred thirty two": "532",
  "five hundred thirty three": "533",
  "five hundred thirty four": "534",
  "five hundred thirty five": "535",
  "five hundred thirty six": "536",
  "five hundred thirty seven": "537",
  "five hundred thirty eight": "538",
  "five hundred thirty nine": "539",
  "five hundred forty": "540",
  "five hundred forty one": "541",
  "five hundred forty two": "542",
  "five hundred forty three": "543",
  "five hundred forty four": "544",
  "five hundred forty five": "545",
  "five hundred forty six": "546",
  "five hundred forty seven": "547",
  "five hundred forty eight": "548",
  "five hundred forty nine": "549",
  "five hundred fifty": "550",
  "five hundred fifty one": "551",
  "five hundred fifty two": "552",
  "five hundred fifty three": "553",
  "five hundred fifty four": "554",
  "five hundred fifty five": "555",
  "five hundred fifty six": "556",
  "five hundred fifty seven": "557",
  "five hundred fifty eight": "558",
  "five hundred fifty nine": "559",
  "five hundred sixty": "560",
  "five hundred sixty one": "561",
  "five hundred sixty two": "562",
  "five hundred sixty three": "563",
  "five hundred sixty four": "564",
  "five hundred sixty five": "565",
  "five hundred sixty six": "566",
  "five hundred sixty seven": "567",
  "five hundred sixty eight": "568",
  "five hundred sixty nine": "569",
  "five hundred seventy": "570",
  "five hundred seventy one": "571",
  "five hundred seventy two": "572",
  "five hundred seventy three": "573",
  "five hundred seventy four": "574",
  "five hundred seventy five": "575",
  "five hundred seventy six": "576",
  "five hundred seventy seven": "577",
  "five hundred seventy eight": "578",
  "five hundred seventy nine": "579",
  "five hundred eighty": "580",
  "five hundred eighty one": "581",
  "five hundred eighty two": "582",
  "five hundred eighty three": "583",
  "five hundred eighty four": "584",
  "five hundred eighty five": "585",
  "five hundred eighty six": "586",
  "five hundred eighty seven": "587",
  "five hundred eighty eight": "588",
  "five hundred eighty nine": "589",
  "five hundred ninety": "590",
  "five hundred ninety one": "591",
  "five hundred ninety two": "592",
  "five hundred ninety three": "593",
  "five hundred ninety four": "594",
  "five hundred ninety five": "595",
  "five hundred ninety six": "596",
  "five hundred ninety seven": "597",
  "five hundred ninety eight": "598",
  "five hundred ninety nine": "599",
  "six hundred": "600",
  "six hundred one": "601",
  "six hundred two": "602",
  "six hundred three": "603",
  "six hundred four": "604",
  "six hundred five": "605",
  "six hundred six": "606",
  "six hundred seven": "607",
  "six hundred eight": "608",
  "six hundred nine": "609",
  "six hundred ten": "610",
  "six hundred eleven": "611",
  "six hundred twelve": "612",
  "six hundred thirteen": "613",
  "six hundred fourteen": "614",
  "six hundred fifteen": "615",
  "six hundred sixteen": "616",
  "six hundred seventeen": "617",
  "six hundred eighteen": "618",
  "six hundred nineteen": "619",
  "six hundred twenty": "620",
  "six hundred twenty one": "621",
  "six hundred twenty two": "622",
  "six hundred twenty three": "623",
  "six hundred twenty four": "624",
  "six hundred twenty five": "625",
  "six hundred twenty six": "626",
  "six hundred twenty seven": "627",
  "six hundred twenty eight": "628",
  "six hundred twenty nine": "629",
  "six hundred thirty": "630",
  "six hundred thirty one": "631",
  "six hundred thirty two": "632",
  "six hundred thirty three": "633",
  "six hundred thirty four": "634",
  "six hundred thirty five": "635",
  "six hundred thirty six": "636",
  "six hundred thirty seven": "637",
  "six hundred thirty eight": "638",
  "six hundred thirty nine": "639",
  "six hundred forty": "640",
  "six hundred forty one": "641",
  "six hundred forty two": "642",
  "six hundred forty three": "643",
  "six hundred forty four": "644",
  "six hundred forty five": "645",
  "six hundred forty six": "646",
  "six hundred forty seven": "647",
  "six hundred forty eight": "648",
  "six hundred forty nine": "649",
  "six hundred fifty": "650",
  "six hundred fifty one": "651",
  "six hundred fifty two": "652",
  "six hundred fifty three": "653",
  "six hundred fifty four": "654",
  "six hundred fifty five": "655",
  "six hundred fifty six": "656",
  "six hundred fifty seven": "657",
  "six hundred fifty eight": "658",
  "six hundred fifty nine": "659",
  "six hundred sixty": "660",
  "six hundred sixty one": "661",
  "six hundred sixty two": "662",
  "six hundred sixty three": "663",
  "six hundred sixty four": "664",
  "six hundred sixty five": "665",
  "six hundred sixty six": "666",
  "six hundred sixty seven": "667",
  "six hundred sixty eight": "668",
  "six hundred sixty nine": "669",
  "six hundred seventy": "670",
  "six hundred seventy one": "671",
  "six hundred seventy two": "672",
  "six hundred seventy three": "673",
  "six hundred seventy four": "674",
  "six hundred seventy five": "675",
  "six hundred seventy six": "676",
  "six hundred seventy seven": "677",
  "six hundred seventy eight": "678",
  "six hundred seventy nine": "679",
  "six hundred eighty": "680",
  "six hundred eighty one": "681",
  "six hundred eighty two": "682",
  "six hundred eighty three": "683",
  "six hundred eighty four": "684",
  "six hundred eighty five": "685",
  "six hundred eighty six": "686",
  "six hundred eighty seven": "687",
  "six hundred eighty eight": "688",
  "six hundred eighty nine": "689",
  "six hundred ninety": "690",
  "six hundred ninety one": "691",
  "six hundred ninety two": "692",
  "six hundred ninety three": "693",
  "six hundred ninety four": "694",
  "six hundred ninety five": "695",
  "six hundred ninety six": "696",
  "six hundred ninety seven": "697",
  "six hundred ninety eight": "698",
  "six hundred ninety nine": "699",
  "seven hundred": "700",
  "seven hundred one": "701",
  "seven hundred two": "702",
  "seven hundred three": "703",
  "seven hundred four": "704",
  "seven hundred five": "705",
  "seven hundred six": "706",
  "seven hundred seven": "707",
  "seven hundred eight": "708",
  "seven hundred nine": "709",
  "seven hundred ten": "710",
  "seven hundred eleven": "711",
  "seven hundred twelve": "712",
  "seven hundred thirteen": "713",
  "seven hundred fourteen": "714",
  "seven hundred fifteen": "715",
  "seven hundred sixteen": "716",
  "seven hundred seventeen": "717",
  "seven hundred eighteen": "718",
  "seven hundred nineteen": "719",
  "seven hundred twenty": "720",
  "seven hundred twenty one": "721",
  "seven hundred twenty two": "722",
  "seven hundred twenty three": "723",
  "seven hundred twenty four": "724",
  "seven hundred twenty five": "725",
  "seven hundred twenty six": "726",
  "seven hundred twenty seven": "727",
  "seven hundred twenty eight": "728",
  "seven hundred twenty nine": "729",
  "seven hundred thirty": "730",
  "seven hundred thirty one": "731",
  "seven hundred thirty two": "732",
  "seven hundred thirty three": "733",
  "seven hundred thirty four": "734",
  "seven hundred thirty five": "735",
  "seven hundred thirty six": "736",
  "seven hundred thirty seven": "737",
  "seven hundred thirty eight": "738",
  "seven hundred thirty nine": "739",
  "seven hundred forty": "740",
  "seven hundred forty one": "741",
  "seven hundred forty two": "742",
  "seven hundred forty three": "743",
  "seven hundred forty four": "744",
  "seven hundred forty five": "745",
  "seven hundred forty six": "746",
  "seven hundred forty seven": "747",
  "seven hundred forty eight": "748",
  "seven hundred forty nine": "749",
  "seven hundred fifty": "750",
  "seven hundred fifty one": "751",
  "seven hundred fifty two": "752",
  "seven hundred fifty three": "753",
  "seven hundred fifty four": "754",
  "seven hundred fifty five": "755",
  "seven hundred fifty six": "756",
  "seven hundred fifty seven": "757",
  "seven hundred fifty eight": "758",
  "seven hundred fifty nine": "759",
  "seven hundred sixty": "760",
  "seven hundred sixty one": "761",
  "seven hundred sixty two": "762",
  "seven hundred sixty three": "763",
  "seven hundred sixty four": "764",
  "seven hundred sixty five": "765",
  "seven hundred sixty six": "766",
  "seven hundred sixty seven": "767",
  "seven hundred sixty eight": "768",
  "seven hundred sixty nine": "769",
  "seven hundred seventy": "770",
  "seven hundred seventy one": "771",
  "seven hundred seventy two": "772",
  "seven hundred seventy three": "773",
  "seven hundred seventy four": "774",
  "seven hundred seventy five": "775",
  "seven hundred seventy six": "776",
  "seven hundred seventy seven": "777",
  "seven hundred seventy eight": "778",
  "seven hundred seventy nine": "779",
  "seven hundred eighty": "780",
  "seven hundred eighty one": "781",
  "seven hundred eighty two": "782",
  "seven hundred eighty three": "783",
  "seven hundred eighty four": "784",
  "seven hundred eighty five": "785",
  "seven hundred eighty six": "786",
  "seven hundred eighty seven": "787",
  "seven hundred eighty eight": "788",
  "seven hundred eighty nine": "789",
  "seven hundred ninety": "790",
  "seven hundred ninety one": "791",
  "seven hundred ninety two": "792",
  "seven hundred ninety three": "793",
  "seven hundred ninety four": "794",
  "seven hundred ninety five": "795",
  "seven hundred ninety six": "796",
  "seven hundred ninety seven": "797",
  "seven hundred ninety eight": "798",
  "seven hundred ninety nine": "799",
  "eight hundred": "800",
  "eight hundred one": "801",
  "eight hundred two": "802",
  "eight hundred three": "803",
  "eight hundred four": "804",
  "eight hundred five": "805",
  "eight hundred six": "806",
  "eight hundred seven": "807",
  "eight hundred eight": "808",
  "eight hundred nine": "809",
  "eight hundred ten": "810",
  "eight hundred eleven": "811",
  "eight hundred twelve": "812",
  "eight hundred thirteen": "813",
  "eight hundred fourteen": "814",
  "eight hundred fifteen": "815",
  "eight hundred sixteen": "816",
  "eight hundred seventeen": "817",
  "eight hundred eighteen": "818",
  "eight hundred nineteen": "819",
  "eight hundred twenty": "820",
  "eight hundred twenty one": "821",
  "eight hundred twenty two": "822",
  "eight hundred twenty three": "823",
  "eight hundred twenty four": "824",
  "eight hundred twenty five": "825",
  "eight hundred twenty six": "826",
  "eight hundred twenty seven": "827",
  "eight hundred twenty eight": "828",
  "eight hundred twenty nine": "829",
  "eight hundred thirty": "830",
  "eight hundred thirty one": "831",
  "eight hundred thirty two": "832",
  "eight hundred thirty three": "833",
  "eight hundred thirty four": "834",
  "eight hundred thirty five": "835",
  "eight hundred thirty six": "836",
  "eight hundred thirty seven": "837",
  "eight hundred thirty eight": "838",
  "eight hundred thirty nine": "839",
  "eight hundred forty": "840",
  "eight hundred forty one": "841",
  "eight hundred forty two": "842",
  "eight hundred forty three": "843",
  "eight hundred forty four": "844",
  "eight hundred forty five": "845",
  "eight hundred forty six": "846",
  "eight hundred forty seven": "847",
  "eight hundred forty eight": "848",
  "eight hundred forty nine": "849",
  "eight hundred fifty": "850",
  "eight hundred fifty one": "851",
  "eight hundred fifty two": "852",
  "eight hundred fifty three": "853",
  "eight hundred fifty four": "854",
  "eight hundred fifty five": "855",
  "eight hundred fifty six": "856",
  "eight hundred fifty seven": "857",
  "eight hundred fifty eight": "858",
  "eight hundred fifty nine": "859",
  "eight hundred sixty": "860",
  "eight hundred sixty one": "861",
  "eight hundred sixty two": "862",
  "eight hundred sixty three": "863",
  "eight hundred sixty four": "864",
  "eight hundred sixty five": "865",
  "eight hundred sixty six": "866",
  "eight hundred sixty seven": "867",
  "eight hundred sixty eight": "868",
  "eight hundred sixty nine": "869",
  "eight hundred seventy": "870",
  "eight hundred seventy one": "871",
  "eight hundred seventy two": "872",
  "eight hundred seventy three": "873",
  "eight hundred seventy four": "874",
  "eight hundred seventy five": "875",
  "eight hundred seventy six": "876",
  "eight hundred seventy seven": "877",
  "eight hundred seventy eight": "878",
  "eight hundred seventy nine": "879",
  "eight hundred eighty": "880",
  "eight hundred eighty one": "881",
  "eight hundred eighty two": "882",
  "eight hundred eighty three": "883",
  "eight hundred eighty four": "884",
  "eight hundred eighty five": "885",
  "eight hundred eighty six": "886",
  "eight hundred eighty seven": "887",
  "eight hundred eighty eight": "888",
  "eight hundred eighty nine": "889",
  "eight hundred ninety": "890",
  "eight hundred ninety one": "891",
  "eight hundred ninety two": "892",
  "eight hundred ninety three": "893",
  "eight hundred ninety four": "894",
  "eight hundred ninety five": "895",
  "eight hundred ninety six": "896",
  "eight hundred ninety seven": "897",
  "eight hundred ninety eight": "898",
  "eight hundred ninety nine": "899",
  "nine hundred": "900",
  "nine hundred one": "901",
  "nine hundred two": "902",
  "nine hundred three": "903",
  "nine hundred four": "904",
  "nine hundred five": "905",
  "nine hundred six": "906",
  "nine hundred seven": "907",
  "nine hundred eight": "908",
  "nine hundred nine": "909",
  "nine hundred ten": "910",
  "nine hundred eleven": "911",
  "nine hundred twelve": "912",
  "nine hundred thirteen": "913",
  "nine hundred fourteen": "914",
  "nine hundred fifteen": "915",
  "nine hundred sixteen": "916",
  "nine hundred seventeen": "917",
  "nine hundred eighteen": "918",
  "nine hundred nineteen": "919",
  "nine hundred twenty": "920",
  "nine hundred twenty one": "921",
  "nine hundred twenty two": "922",
  "nine hundred twenty three": "923",
  "nine hundred twenty four": "924",
  "nine hundred twenty five": "925",
  "nine hundred twenty six": "926",
  "nine hundred twenty seven": "927",
  "nine hundred twenty eight": "928",
  "nine hundred twenty nine": "929",
  "nine hundred thirty": "930",
  "nine hundred thirty one": "931",
  "nine hundred thirty two": "932",
  "nine hundred thirty three": "933",
  "nine hundred thirty four": "934",
  "nine hundred thirty five": "935",
  "nine hundred thirty six": "936",
  "nine hundred thirty seven": "937",
  "nine hundred thirty eight": "938",
  "nine hundred thirty nine": "939",
  "nine hundred forty": "940",
  "nine hundred forty one": "941",
  "nine hundred forty two": "942",
  "nine hundred forty three": "943",
  "nine hundred forty four": "944",
  "nine hundred forty five": "945",
  "nine hundred forty six": "946",
  "nine hundred forty seven": "947",
  "nine hundred forty eight": "948",
  "nine hundred forty nine": "949",
  "nine hundred fifty": "950",
  "nine hundred fifty one": "951",
  "nine hundred fifty two": "952",
  "nine hundred fifty three": "953",
  "nine hundred fifty four": "954",
  "nine hundred fifty five": "955",
  "nine hundred fifty six": "956",
  "nine hundred fifty seven": "957",
  "nine hundred fifty eight": "958",
  "nine hundred fifty nine": "959",
  "nine hundred sixty": "960",
  "nine hundred sixty one": "961",
  "nine hundred sixty two": "962",
  "nine hundred sixty three": "963",
  "nine hundred sixty four": "964",
  "nine hundred sixty five": "965",
  "nine hundred sixty six": "966",
  "nine hundred sixty seven": "967",
  "nine hundred sixty eight": "968",
  "nine hundred sixty nine": "969",
  "nine hundred seventy": "970",
  "nine hundred seventy one": "971",
  "nine hundred seventy two": "972",
  "nine hundred seventy three": "973",
  "nine hundred seventy four": "974",
  "nine hundred seventy five": "975",
  "nine hundred seventy six": "976",
  "nine hundred seventy seven": "977",
  "nine hundred seventy eight": "978",
  "nine hundred seventy nine": "979",
  "nine hundred eighty": "980",
  "nine hundred eighty one": "981",
  "nine hundred eighty two": "982",
  "nine hundred eighty three": "983",
  "nine hundred eighty four": "984",
  "nine hundred eighty five": "985",
  "nine hundred eighty six": "986",
  "nine hundred eighty seven": "987",
  "nine hundred eighty eight": "988",
  "nine hundred eighty nine": "989",
  "nine hundred ninety": "990",
  "nine hundred ninety one": "991",
  "nine hundred ninety two": "992",
  "nine hundred ninety three": "993",
  "nine hundred ninety four": "994",
  "nine hundred ninety five": "995",
  "nine hundred ninety six": "996",
  "nine hundred ninety seven": "997",
  "nine hundred ninety eight": "998",
  "nine hundred ninety nine": "999",
  "one thousand": "1000",
  "first": "1st",
  "second": "2nd",
  "third": "3rd",
  "fourth": "4th",
  "fifth": "5th",
  "sixth": "6th",
  "seventh": "7th",
  "eighth": "8th",
  "ninth": "9th",
  "tenth": "10th",
  "eleventh": "11th",
  "twelfth": "12th",
  "thirteenth": "13th",
  "fourteenth": "14th",
  "fifteenth": "15th",
  "sixteenth": "16th",
  "seventeenth": "17th",
  "eighteenth": "18th",
  "nineteenth": "19th",
  "twentieth": "20th",
  "twentie-first": "21st",
  "twentie-second": "22nd",
  "twentie-third": "23rd",
  "twentie-fourth": "24th",
  "twentie-fifth": "25th",
  "twentie-sixth": "26th",
  "twentie-seventh": "27th",
  "twentie-eighth": "28th",
  "twentie-ninth": "29th",
  "thirtieth": "30th",
  "thirtie-first": "31st",
  "thirtie-second": "32nd",
  "thirtie-third": "33rd",
  "thirtie-fourth": "34th",
  "thirtie-fifth": "35th",
  "thirtie-sixth": "36th",
  "thirtie-seventh": "37th",
  "thirtie-eighth": "38th",
  "thirtie-ninth": "39th",
  "fortieth": "40th",
  "fortie-first": "41st",
  "fortie-second": "42nd",
  "fortie-third": "43rd",
  "fortie-fourth": "44th",
  "fortie-fifth": "45th",
  "fortie-sixth": "46th",
  "fortie-seventh": "47th",
  "fortie-eighth": "48th",
  "fortie-ninth": "49th",
  "fiftieth": "50th",
  "fiftie-first": "51st",
  "fiftie-second": "52nd",
  "fiftie-third": "53rd",
  "fiftie-fourth": "54th",
  "fiftie-fifth": "55th",
  "fiftie-sixth": "56th",
  "fiftie-seventh": "57th",
  "fiftie-eighth": "58th",
  "fiftie-ninth": "59th",
  "sixtieth": "60th",
  "sixtie-first": "61st",
  "sixtie-second": "62nd",
  "sixtie-third": "63rd",
  "sixtie-fourth": "64th",
  "sixtie-fifth": "65th",
  "sixtie-sixth": "66th",
  "sixtie-seventh": "67th",
  "sixtie-eighth": "68th",
  "sixtie-ninth": "69th",
  "seventieth": "70th",
  "seventie-first": "71st",
  "seventie-second": "72nd",
  "seventie-third": "73rd",
  "seventie-fourth": "74th",
  "seventie-fifth": "75th",
  "seventie-sixth": "76th",
  "seventie-seventh": "77th",
  "seventie-eighth": "78th",
  "seventie-ninth": "79th",
  "eightieth": "80th",
  "eightie-first": "81st",
  "eightie-second": "82nd",
  "eightie-third": "83rd",
  "eightie-fourth": "84th",
  "eightie-fifth": "85th",
  "eightie-sixth": "86th",
  "eightie-seventh": "87th",
  "eightie-eighth": "88th",
  "eightie-ninth": "89th",
  "ninetieth": "90th",
  "ninetie-first": "91st",
  "ninetie-second": "92nd",
  "ninetie-third": "93rd",
  "ninetie-fourth": "94th",
  "ninetie-fifth": "95th",
  "ninetie-sixth": "96th",
  "ninetie-seventh": "97th",
  "ninetie-eighth": "98th",
  "ninetie-ninth": "99th",
  "hundredth": "100th",
  "one hundredth": "100th",
  "second hundredths": "200th",
  "third hundredths": "300th",
  "fourth hundredths": "400th",
  "fifth hundredths": "500th",
  "sixth hundredths": "600th",
  "seventh hundredths": "700th",
  "eighth hundredths": "800th",
  "ninth hundredths": "900th",
  "tenth hundredths": "1000th",
  "first hundredth": "100thth",
  "first hundred first": "101st",
  "first hundred second": "102nd",
  "first hundred third": "103rd",
  "first hundred fourth": "104th",
  "first hundred fifth": "105th",
  "first hundred sixth": "106th",
  "first hundred seventh": "107th",
  "first hundred eighth": "108th",
  "first hundred ninth": "109th",
  "first hundred tenth": "110th",
  "first hundred eleventh": "111th",
  "first hundred twelfth": "112th",
  "first hundred thirteenth": "113th",
  "first hundred fourteenth": "114th",
  "first hundred fifteenth": "115th",
  "first hundred sixteenth": "116th",
  "first hundred seventeenth": "117th",
  "first hundred eighteenth": "118th",
  "first hundred nineteenth": "119th",
  "first hundred twentieth": "120th",
  "first hundred twentie-first": "121st",
  "first hundred twentie-second": "122nd",
  "first hundred twentie-third": "123rd",
  "first hundred twentie-fourth": "124th",
  "first hundred twentie-fifth": "125th",
  "first hundred twentie-sixth": "126th",
  "first hundred twentie-seventh": "127th",
  "first hundred twentie-eighth": "128th",
  "first hundred twentie-ninth": "129th",
  "first hundred thirtieth": "130th",
  "first hundred thirtie-first": "131st",
  "first hundred thirtie-second": "132nd",
  "first hundred thirtie-third": "133rd",
  "first hundred thirtie-fourth": "134th",
  "first hundred thirtie-fifth": "135th",
  "first hundred thirtie-sixth": "136th",
  "first hundred thirtie-seventh": "137th",
  "first hundred thirtie-eighth": "138th",
  "first hundred thirtie-ninth": "139th",
  "first hundred fortieth": "140th",
  "first hundred fortie-first": "141st",
  "first hundred fortie-second": "142nd",
  "first hundred fortie-third": "143rd",
  "first hundred fortie-fourth": "144th",
  "first hundred fortie-fifth": "145th",
  "first hundred fortie-sixth": "146th",
  "first hundred fortie-seventh": "147th",
  "first hundred fortie-eighth": "148th",
  "first hundred fortie-ninth": "149th",
  "first hundred fiftieth": "150th",
  "first hundred fiftie-first": "151st",
  "first hundred fiftie-second": "152nd",
  "first hundred fiftie-third": "153rd",
  "first hundred fiftie-fourth": "154th",
  "first hundred fiftie-fifth": "155th",
  "first hundred fiftie-sixth": "156th",
  "first hundred fiftie-seventh": "157th",
  "first hundred fiftie-eighth": "158th",
  "first hundred fiftie-ninth": "159th",
  "first hundred sixtieth": "160th",
  "first hundred sixtie-first": "161st",
  "first hundred sixtie-second": "162nd",
  "first hundred sixtie-third": "163rd",
  "first hundred sixtie-fourth": "164th",
  "first hundred sixtie-fifth": "165th",
  "first hundred sixtie-sixth": "166th",
  "first hundred sixtie-seventh": "167th",
  "first hundred sixtie-eighth": "168th",
  "first hundred sixtie-ninth": "169th",
  "first hundred seventieth": "170th",
  "first hundred seventie-first": "171st",
  "first hundred seventie-second": "172nd",
  "first hundred seventie-third": "173rd",
  "first hundred seventie-fourth": "174th",
  "first hundred seventie-fifth": "175th",
  "first hundred seventie-sixth": "176th",
  "first hundred seventie-seventh": "177th",
  "first hundred seventie-eighth": "178th",
  "first hundred seventie-ninth": "179th",
  "first hundred eightieth": "180th",
  "first hundred eightie-first": "181st",
  "first hundred eightie-second": "182nd",
  "first hundred eightie-third": "183rd",
  "first hundred eightie-fourth": "184th",
  "first hundred eightie-fifth": "185th",
  "first hundred eightie-sixth": "186th",
  "first hundred eightie-seventh": "187th",
  "first hundred eightie-eighth": "188th",
  "first hundred eightie-ninth": "189th",
  "first hundred ninetieth": "190th",
  "first hundred ninetie-first": "191st",
  "first hundred ninetie-second": "192nd",
  "first hundred ninetie-third": "193rd",
  "first hundred ninetie-fourth": "194th",
  "first hundred ninetie-fifth": "195th",
  "first hundred ninetie-sixth": "196th",
  "first hundred ninetie-seventh": "197th",
  "first hundred ninetie-eighth": "198th",
  "first hundred ninetie-ninth": "199th",
  "second hundredth": "200th",
  "second hundred first": "201st",
  "second hundred second": "202nd",
  "second hundred third": "203rd",
  "second hundred fourth": "204th",
  "second hundred fifth": "205th",
  "second hundred sixth": "206th",
  "second hundred seventh": "207th",
  "second hundred eighth": "208th",
  "second hundred ninth": "209th",
  "second hundred tenth": "210th",
  "second hundred eleventh": "211th",
  "second hundred twelfth": "212th",
  "second hundred thirteenth": "213th",
  "second hundred fourteenth": "214th",
  "second hundred fifteenth": "215th",
  "second hundred sixteenth": "216th",
  "second hundred seventeenth": "217th",
  "second hundred eighteenth": "218th",
  "second hundred nineteenth": "219th",
  "second hundred twentieth": "220th",
  "second hundred twentie-first": "221st",
  "second hundred twentie-second": "222nd",
  "second hundred twentie-third": "223rd",
  "second hundred twentie-fourth": "224th",
  "second hundred twentie-fifth": "225th",
  "second hundred twentie-sixth": "226th",
  "second hundred twentie-seventh": "227th",
  "second hundred twentie-eighth": "228th",
  "second hundred twentie-ninth": "229th",
  "second hundred thirtieth": "230th",
  "second hundred thirtie-first": "231st",
  "second hundred thirtie-second": "232nd",
  "second hundred thirtie-third": "233rd",
  "second hundred thirtie-fourth": "234th",
  "second hundred thirtie-fifth": "235th",
  "second hundred thirtie-sixth": "236th",
  "second hundred thirtie-seventh": "237th",
  "second hundred thirtie-eighth": "238th",
  "second hundred thirtie-ninth": "239th",
  "second hundred fortieth": "240th",
  "second hundred fortie-first": "241st",
  "second hundred fortie-second": "242nd",
  "second hundred fortie-third": "243rd",
  "second hundred fortie-fourth": "244th",
  "second hundred fortie-fifth": "245th",
  "second hundred fortie-sixth": "246th",
  "second hundred fortie-seventh": "247th",
  "second hundred fortie-eighth": "248th",
  "second hundred fortie-ninth": "249th",
  "second hundred fiftieth": "250th",
  "second hundred fiftie-first": "251st",
  "second hundred fiftie-second": "252nd",
  "second hundred fiftie-third": "253rd",
  "second hundred fiftie-fourth": "254th",
  "second hundred fiftie-fifth": "255th",
  "second hundred fiftie-sixth": "256th",
  "second hundred fiftie-seventh": "257th",
  "second hundred fiftie-eighth": "258th",
  "second hundred fiftie-ninth": "259th",
  "second hundred sixtieth": "260th",
  "second hundred sixtie-first": "261st",
  "second hundred sixtie-second": "262nd",
  "second hundred sixtie-third": "263rd",
  "second hundred sixtie-fourth": "264th",
  "second hundred sixtie-fifth": "265th",
  "second hundred sixtie-sixth": "266th",
  "second hundred sixtie-seventh": "267th",
  "second hundred sixtie-eighth": "268th",
  "second hundred sixtie-ninth": "269th",
  "second hundred seventieth": "270th",
  "second hundred seventie-first": "271st",
  "second hundred seventie-second": "272nd",
  "second hundred seventie-third": "273rd",
  "second hundred seventie-fourth": "274th",
  "second hundred seventie-fifth": "275th",
  "second hundred seventie-sixth": "276th",
  "second hundred seventie-seventh": "277th",
  "second hundred seventie-eighth": "278th",
  "second hundred seventie-ninth": "279th",
  "second hundred eightieth": "280th",
  "second hundred eightie-first": "281st",
  "second hundred eightie-second": "282nd",
  "second hundred eightie-third": "283rd",
  "second hundred eightie-fourth": "284th",
  "second hundred eightie-fifth": "285th",
  "second hundred eightie-sixth": "286th",
  "second hundred eightie-seventh": "287th",
  "second hundred eightie-eighth": "288th",
  "second hundred eightie-ninth": "289th",
  "second hundred ninetieth": "290th",
  "second hundred ninetie-first": "291st",
  "second hundred ninetie-second": "292nd",
  "second hundred ninetie-third": "293rd",
  "second hundred ninetie-fourth": "294th",
  "second hundred ninetie-fifth": "295th",
  "second hundred ninetie-sixth": "296th",
  "second hundred ninetie-seventh": "297th",
  "second hundred ninetie-eighth": "298th",
  "second hundred ninetie-ninth": "299th",
  "third hundredth": "300th",
  "third hundred first": "301st",
  "third hundred second": "302nd",
  "third hundred third": "303rd",
  "third hundred fourth": "304th",
  "third hundred fifth": "305th",
  "third hundred sixth": "306th",
  "third hundred seventh": "307th",
  "third hundred eighth": "308th",
  "third hundred ninth": "309th",
  "third hundred tenth": "310th",
  "third hundred eleventh": "311th",
  "third hundred twelfth": "312th",
  "third hundred thirteenth": "313th",
  "third hundred fourteenth": "314th",
  "third hundred fifteenth": "315th",
  "third hundred sixteenth": "316th",
  "third hundred seventeenth": "317th",
  "third hundred eighteenth": "318th",
  "third hundred nineteenth": "319th",
  "third hundred twentieth": "320th",
  "third hundred twentie-first": "321st",
  "third hundred twentie-second": "322nd",
  "third hundred twentie-third": "323rd",
  "third hundred twentie-fourth": "324th",
  "third hundred twentie-fifth": "325th",
  "third hundred twentie-sixth": "326th",
  "third hundred twentie-seventh": "327th",
  "third hundred twentie-eighth": "328th",
  "third hundred twentie-ninth": "329th",
  "third hundred thirtieth": "330th",
  "third hundred thirtie-first": "331st",
  "third hundred thirtie-second": "332nd",
  "third hundred thirtie-third": "333rd",
  "third hundred thirtie-fourth": "334th",
  "third hundred thirtie-fifth": "335th",
  "third hundred thirtie-sixth": "336th",
  "third hundred thirtie-seventh": "337th",
  "third hundred thirtie-eighth": "338th",
  "third hundred thirtie-ninth": "339th",
  "third hundred fortieth": "340th",
  "third hundred fortie-first": "341st",
  "third hundred fortie-second": "342nd",
  "third hundred fortie-third": "343rd",
  "third hundred fortie-fourth": "344th",
  "third hundred fortie-fifth": "345th",
  "third hundred fortie-sixth": "346th",
  "third hundred fortie-seventh": "347th",
  "third hundred fortie-eighth": "348th",
  "third hundred fortie-ninth": "349th",
  "third hundred fiftieth": "350th",
  "third hundred fiftie-first": "351st",
  "third hundred fiftie-second": "352nd",
  "third hundred fiftie-third": "353rd",
  "third hundred fiftie-fourth": "354th",
  "third hundred fiftie-fifth": "355th",
  "third hundred fiftie-sixth": "356th",
  "third hundred fiftie-seventh": "357th",
  "third hundred fiftie-eighth": "358th",
  "third hundred fiftie-ninth": "359th",
  "third hundred sixtieth": "360th",
  "third hundred sixtie-first": "361st",
  "third hundred sixtie-second": "362nd",
  "third hundred sixtie-third": "363rd",
  "third hundred sixtie-fourth": "364th",
  "third hundred sixtie-fifth": "365th",
  "third hundred sixtie-sixth": "366th",
  "third hundred sixtie-seventh": "367th",
  "third hundred sixtie-eighth": "368th",
  "third hundred sixtie-ninth": "369th",
  "third hundred seventieth": "370th",
  "third hundred seventie-first": "371st",
  "third hundred seventie-second": "372nd",
  "third hundred seventie-third": "373rd",
  "third hundred seventie-fourth": "374th",
  "third hundred seventie-fifth": "375th",
  "third hundred seventie-sixth": "376th",
  "third hundred seventie-seventh": "377th",
  "third hundred seventie-eighth": "378th",
  "third hundred seventie-ninth": "379th",
  "third hundred eightieth": "380th",
  "third hundred eightie-first": "381st",
  "third hundred eightie-second": "382nd",
  "third hundred eightie-third": "383rd",
  "third hundred eightie-fourth": "384th",
  "third hundred eightie-fifth": "385th",
  "third hundred eightie-sixth": "386th",
  "third hundred eightie-seventh": "387th",
  "third hundred eightie-eighth": "388th",
  "third hundred eightie-ninth": "389th",
  "third hundred ninetieth": "390th",
  "third hundred ninetie-first": "391st",
  "third hundred ninetie-second": "392nd",
  "third hundred ninetie-third": "393rd",
  "third hundred ninetie-fourth": "394th",
  "third hundred ninetie-fifth": "395th",
  "third hundred ninetie-sixth": "396th",
  "third hundred ninetie-seventh": "397th",
  "third hundred ninetie-eighth": "398th",
  "third hundred ninetie-ninth": "399th",
  "fourth hundredth": "400th",
  "fourth hundred first": "401st",
  "fourth hundred second": "402nd",
  "fourth hundred third": "403rd",
  "fourth hundred fourth": "404th",
  "fourth hundred fifth": "405th",
  "fourth hundred sixth": "406th",
  "fourth hundred seventh": "407th",
  "fourth hundred eighth": "408th",
  "fourth hundred ninth": "409th",
  "fourth hundred tenth": "410th",
  "fourth hundred eleventh": "411th",
  "fourth hundred twelfth": "412th",
  "fourth hundred thirteenth": "413th",
  "fourth hundred fourteenth": "414th",
  "fourth hundred fifteenth": "415th",
  "fourth hundred sixteenth": "416th",
  "fourth hundred seventeenth": "417th",
  "fourth hundred eighteenth": "418th",
  "fourth hundred nineteenth": "419th",
  "fourth hundred twentieth": "420th",
  "fourth hundred twentie-first": "421st",
  "fourth hundred twentie-second": "422nd",
  "fourth hundred twentie-third": "423rd",
  "fourth hundred twentie-fourth": "424th",
  "fourth hundred twentie-fifth": "425th",
  "fourth hundred twentie-sixth": "426th",
  "fourth hundred twentie-seventh": "427th",
  "fourth hundred twentie-eighth": "428th",
  "fourth hundred twentie-ninth": "429th",
  "fourth hundred thirtieth": "430th",
  "fourth hundred thirtie-first": "431st",
  "fourth hundred thirtie-second": "432nd",
  "fourth hundred thirtie-third": "433rd",
  "fourth hundred thirtie-fourth": "434th",
  "fourth hundred thirtie-fifth": "435th",
  "fourth hundred thirtie-sixth": "436th",
  "fourth hundred thirtie-seventh": "437th",
  "fourth hundred thirtie-eighth": "438th",
  "fourth hundred thirtie-ninth": "439th",
  "fourth hundred fortieth": "440th",
  "fourth hundred fortie-first": "441st",
  "fourth hundred fortie-second": "442nd",
  "fourth hundred fortie-third": "443rd",
  "fourth hundred fortie-fourth": "444th",
  "fourth hundred fortie-fifth": "445th",
  "fourth hundred fortie-sixth": "446th",
  "fourth hundred fortie-seventh": "447th",
  "fourth hundred fortie-eighth": "448th",
  "fourth hundred fortie-ninth": "449th",
  "fourth hundred fiftieth": "450th",
  "fourth hundred fiftie-first": "451st",
  "fourth hundred fiftie-second": "452nd",
  "fourth hundred fiftie-third": "453rd",
  "fourth hundred fiftie-fourth": "454th",
  "fourth hundred fiftie-fifth": "455th",
  "fourth hundred fiftie-sixth": "456th",
  "fourth hundred fiftie-seventh": "457th",
  "fourth hundred fiftie-eighth": "458th",
  "fourth hundred fiftie-ninth": "459th",
  "fourth hundred sixtieth": "460th",
  "fourth hundred sixtie-first": "461st",
  "fourth hundred sixtie-second": "462nd",
  "fourth hundred sixtie-third": "463rd",
  "fourth hundred sixtie-fourth": "464th",
  "fourth hundred sixtie-fifth": "465th",
  "fourth hundred sixtie-sixth": "466th",
  "fourth hundred sixtie-seventh": "467th",
  "fourth hundred sixtie-eighth": "468th",
  "fourth hundred sixtie-ninth": "469th",
  "fourth hundred seventieth": "470th",
  "fourth hundred seventie-first": "471st",
  "fourth hundred seventie-second": "472nd",
  "fourth hundred seventie-third": "473rd",
  "fourth hundred seventie-fourth": "474th",
  "fourth hundred seventie-fifth": "475th",
  "fourth hundred seventie-sixth": "476th",
  "fourth hundred seventie-seventh": "477th",
  "fourth hundred seventie-eighth": "478th",
  "fourth hundred seventie-ninth": "479th",
  "fourth hundred eightieth": "480th",
  "fourth hundred eightie-first": "481st",
  "fourth hundred eightie-second": "482nd",
  "fourth hundred eightie-third": "483rd",
  "fourth hundred eightie-fourth": "484th",
  "fourth hundred eightie-fifth": "485th",
  "fourth hundred eightie-sixth": "486th",
  "fourth hundred eightie-seventh": "487th",
  "fourth hundred eightie-eighth": "488th",
  "fourth hundred eightie-ninth": "489th",
  "fourth hundred ninetieth": "490th",
  "fourth hundred ninetie-first": "491st",
  "fourth hundred ninetie-second": "492nd",
  "fourth hundred ninetie-third": "493rd",
  "fourth hundred ninetie-fourth": "494th",
  "fourth hundred ninetie-fifth": "495th",
  "fourth hundred ninetie-sixth": "496th",
  "fourth hundred ninetie-seventh": "497th",
  "fourth hundred ninetie-eighth": "498th",
  "fourth hundred ninetie-ninth": "499th",
  "fifth hundredth": "500th",
  "fifth hundred first": "501st",
  "fifth hundred second": "502nd",
  "fifth hundred third": "503rd",
  "fifth hundred fourth": "504th",
  "fifth hundred fifth": "505th",
  "fifth hundred sixth": "506th",
  "fifth hundred seventh": "507th",
  "fifth hundred eighth": "508th",
  "fifth hundred ninth": "509th",
  "fifth hundred tenth": "510th",
  "fifth hundred eleventh": "511th",
  "fifth hundred twelfth": "512th",
  "fifth hundred thirteenth": "513th",
  "fifth hundred fourteenth": "514th",
  "fifth hundred fifteenth": "515th",
  "fifth hundred sixteenth": "516th",
  "fifth hundred seventeenth": "517th",
  "fifth hundred eighteenth": "518th",
  "fifth hundred nineteenth": "519th",
  "fifth hundred twentieth": "520th",
  "fifth hundred twentie-first": "521st",
  "fifth hundred twentie-second": "522nd",
  "fifth hundred twentie-third": "523rd",
  "fifth hundred twentie-fourth": "524th",
  "fifth hundred twentie-fifth": "525th",
  "fifth hundred twentie-sixth": "526th",
  "fifth hundred twentie-seventh": "527th",
  "fifth hundred twentie-eighth": "528th",
  "fifth hundred twentie-ninth": "529th",
  "fifth hundred thirtieth": "530th",
  "fifth hundred thirtie-first": "531st",
  "fifth hundred thirtie-second": "532nd",
  "fifth hundred thirtie-third": "533rd",
  "fifth hundred thirtie-fourth": "534th",
  "fifth hundred thirtie-fifth": "535th",
  "fifth hundred thirtie-sixth": "536th",
  "fifth hundred thirtie-seventh": "537th",
  "fifth hundred thirtie-eighth": "538th",
  "fifth hundred thirtie-ninth": "539th",
  "fifth hundred fortieth": "540th",
  "fifth hundred fortie-first": "541st",
  "fifth hundred fortie-second": "542nd",
  "fifth hundred fortie-third": "543rd",
  "fifth hundred fortie-fourth": "544th",
  "fifth hundred fortie-fifth": "545th",
  "fifth hundred fortie-sixth": "546th",
  "fifth hundred fortie-seventh": "547th",
  "fifth hundred fortie-eighth": "548th",
  "fifth hundred fortie-ninth": "549th",
  "fifth hundred fiftieth": "550th",
  "fifth hundred fiftie-first": "551st",
  "fifth hundred fiftie-second": "552nd",
  "fifth hundred fiftie-third": "553rd",
  "fifth hundred fiftie-fourth": "554th",
  "fifth hundred fiftie-fifth": "555th",
  "fifth hundred fiftie-sixth": "556th",
  "fifth hundred fiftie-seventh": "557th",
  "fifth hundred fiftie-eighth": "558th",
  "fifth hundred fiftie-ninth": "559th",
  "fifth hundred sixtieth": "560th",
  "fifth hundred sixtie-first": "561st",
  "fifth hundred sixtie-second": "562nd",
  "fifth hundred sixtie-third": "563rd",
  "fifth hundred sixtie-fourth": "564th",
  "fifth hundred sixtie-fifth": "565th",
  "fifth hundred sixtie-sixth": "566th",
  "fifth hundred sixtie-seventh": "567th",
  "fifth hundred sixtie-eighth": "568th",
  "fifth hundred sixtie-ninth": "569th",
  "fifth hundred seventieth": "570th",
  "fifth hundred seventie-first": "571st",
  "fifth hundred seventie-second": "572nd",
  "fifth hundred seventie-third": "573rd",
  "fifth hundred seventie-fourth": "574th",
  "fifth hundred seventie-fifth": "575th",
  "fifth hundred seventie-sixth": "576th",
  "fifth hundred seventie-seventh": "577th",
  "fifth hundred seventie-eighth": "578th",
  "fifth hundred seventie-ninth": "579th",
  "fifth hundred eightieth": "580th",
  "fifth hundred eightie-first": "581st",
  "fifth hundred eightie-second": "582nd",
  "fifth hundred eightie-third": "583rd",
  "fifth hundred eightie-fourth": "584th",
  "fifth hundred eightie-fifth": "585th",
  "fifth hundred eightie-sixth": "586th",
  "fifth hundred eightie-seventh": "587th",
  "fifth hundred eightie-eighth": "588th",
  "fifth hundred eightie-ninth": "589th",
  "fifth hundred ninetieth": "590th",
  "fifth hundred ninetie-first": "591st",
  "fifth hundred ninetie-second": "592nd",
  "fifth hundred ninetie-third": "593rd",
  "fifth hundred ninetie-fourth": "594th",
  "fifth hundred ninetie-fifth": "595th",
  "fifth hundred ninetie-sixth": "596th",
  "fifth hundred ninetie-seventh": "597th",
  "fifth hundred ninetie-eighth": "598th",
  "fifth hundred ninetie-ninth": "599th",
  "sixth hundredth": "600th",
  "sixth hundred first": "601st",
  "sixth hundred second": "602nd",
  "sixth hundred third": "603rd",
  "sixth hundred fourth": "604th",
  "sixth hundred fifth": "605th",
  "sixth hundred sixth": "606th",
  "sixth hundred seventh": "607th",
  "sixth hundred eighth": "608th",
  "sixth hundred ninth": "609th",
  "sixth hundred tenth": "610th",
  "sixth hundred eleventh": "611th",
  "sixth hundred twelfth": "612th",
  "sixth hundred thirteenth": "613th",
  "sixth hundred fourteenth": "614th",
  "sixth hundred fifteenth": "615th",
  "sixth hundred sixteenth": "616th",
  "sixth hundred seventeenth": "617th",
  "sixth hundred eighteenth": "618th",
  "sixth hundred nineteenth": "619th",
  "sixth hundred twentieth": "620th",
  "sixth hundred twentie-first": "621st",
  "sixth hundred twentie-second": "622nd",
  "sixth hundred twentie-third": "623rd",
  "sixth hundred twentie-fourth": "624th",
  "sixth hundred twentie-fifth": "625th",
  "sixth hundred twentie-sixth": "626th",
  "sixth hundred twentie-seventh": "627th",
  "sixth hundred twentie-eighth": "628th",
  "sixth hundred twentie-ninth": "629th",
  "sixth hundred thirtieth": "630th",
  "sixth hundred thirtie-first": "631st",
  "sixth hundred thirtie-second": "632nd",
  "sixth hundred thirtie-third": "633rd",
  "sixth hundred thirtie-fourth": "634th",
  "sixth hundred thirtie-fifth": "635th",
  "sixth hundred thirtie-sixth": "636th",
  "sixth hundred thirtie-seventh": "637th",
  "sixth hundred thirtie-eighth": "638th",
  "sixth hundred thirtie-ninth": "639th",
  "sixth hundred fortieth": "640th",
  "sixth hundred fortie-first": "641st",
  "sixth hundred fortie-second": "642nd",
  "sixth hundred fortie-third": "643rd",
  "sixth hundred fortie-fourth": "644th",
  "sixth hundred fortie-fifth": "645th",
  "sixth hundred fortie-sixth": "646th",
  "sixth hundred fortie-seventh": "647th",
  "sixth hundred fortie-eighth": "648th",
  "sixth hundred fortie-ninth": "649th",
  "sixth hundred fiftieth": "650th",
  "sixth hundred fiftie-first": "651st",
  "sixth hundred fiftie-second": "652nd",
  "sixth hundred fiftie-third": "653rd",
  "sixth hundred fiftie-fourth": "654th",
  "sixth hundred fiftie-fifth": "655th",
  "sixth hundred fiftie-sixth": "656th",
  "sixth hundred fiftie-seventh": "657th",
  "sixth hundred fiftie-eighth": "658th",
  "sixth hundred fiftie-ninth": "659th",
  "sixth hundred sixtieth": "660th",
  "sixth hundred sixtie-first": "661st",
  "sixth hundred sixtie-second": "662nd",
  "sixth hundred sixtie-third": "663rd",
  "sixth hundred sixtie-fourth": "664th",
  "sixth hundred sixtie-fifth": "665th",
  "sixth hundred sixtie-sixth": "666th",
  "sixth hundred sixtie-seventh": "667th",
  "sixth hundred sixtie-eighth": "668th",
  "sixth hundred sixtie-ninth": "669th",
  "sixth hundred seventieth": "670th",
  "sixth hundred seventie-first": "671st",
  "sixth hundred seventie-second": "672nd",
  "sixth hundred seventie-third": "673rd",
  "sixth hundred seventie-fourth": "674th",
  "sixth hundred seventie-fifth": "675th",
  "sixth hundred seventie-sixth": "676th",
  "sixth hundred seventie-seventh": "677th",
  "sixth hundred seventie-eighth": "678th",
  "sixth hundred seventie-ninth": "679th",
  "sixth hundred eightieth": "680th",
  "sixth hundred eightie-first": "681st",
  "sixth hundred eightie-second": "682nd",
  "sixth hundred eightie-third": "683rd",
  "sixth hundred eightie-fourth": "684th",
  "sixth hundred eightie-fifth": "685th",
  "sixth hundred eightie-sixth": "686th",
  "sixth hundred eightie-seventh": "687th",
  "sixth hundred eightie-eighth": "688th",
  "sixth hundred eightie-ninth": "689th",
  "sixth hundred ninetieth": "690th",
  "sixth hundred ninetie-first": "691st",
  "sixth hundred ninetie-second": "692nd",
  "sixth hundred ninetie-third": "693rd",
  "sixth hundred ninetie-fourth": "694th",
  "sixth hundred ninetie-fifth": "695th",
  "sixth hundred ninetie-sixth": "696th",
  "sixth hundred ninetie-seventh": "697th",
  "sixth hundred ninetie-eighth": "698th",
  "sixth hundred ninetie-ninth": "699th",
  "seventh hundredth": "700th",
  "seventh hundred first": "701st",
  "seventh hundred second": "702nd",
  "seventh hundred third": "703rd",
  "seventh hundred fourth": "704th",
  "seventh hundred fifth": "705th",
  "seventh hundred sixth": "706th",
  "seventh hundred seventh": "707th",
  "seventh hundred eighth": "708th",
  "seventh hundred ninth": "709th",
  "seventh hundred tenth": "710th",
  "seventh hundred eleventh": "711th",
  "seventh hundred twelfth": "712th",
  "seventh hundred thirteenth": "713th",
  "seventh hundred fourteenth": "714th",
  "seventh hundred fifteenth": "715th",
  "seventh hundred sixteenth": "716th",
  "seventh hundred seventeenth": "717th",
  "seventh hundred eighteenth": "718th",
  "seventh hundred nineteenth": "719th",
  "seventh hundred twentieth": "720th",
  "seventh hundred twentie-first": "721st",
  "seventh hundred twentie-second": "722nd",
  "seventh hundred twentie-third": "723rd",
  "seventh hundred twentie-fourth": "724th",
  "seventh hundred twentie-fifth": "725th",
  "seventh hundred twentie-sixth": "726th",
  "seventh hundred twentie-seventh": "727th",
  "seventh hundred twentie-eighth": "728th",
  "seventh hundred twentie-ninth": "729th",
  "seventh hundred thirtieth": "730th",
  "seventh hundred thirtie-first": "731st",
  "seventh hundred thirtie-second": "732nd",
  "seventh hundred thirtie-third": "733rd",
  "seventh hundred thirtie-fourth": "734th",
  "seventh hundred thirtie-fifth": "735th",
  "seventh hundred thirtie-sixth": "736th",
  "seventh hundred thirtie-seventh": "737th",
  "seventh hundred thirtie-eighth": "738th",
  "seventh hundred thirtie-ninth": "739th",
  "seventh hundred fortieth": "740th",
  "seventh hundred fortie-first": "741st",
  "seventh hundred fortie-second": "742nd",
  "seventh hundred fortie-third": "743rd",
  "seventh hundred fortie-fourth": "744th",
  "seventh hundred fortie-fifth": "745th",
  "seventh hundred fortie-sixth": "746th",
  "seventh hundred fortie-seventh": "747th",
  "seventh hundred fortie-eighth": "748th",
  "seventh hundred fortie-ninth": "749th",
  "seventh hundred fiftieth": "750th",
  "seventh hundred fiftie-first": "751st",
  "seventh hundred fiftie-second": "752nd",
  "seventh hundred fiftie-third": "753rd",
  "seventh hundred fiftie-fourth": "754th",
  "seventh hundred fiftie-fifth": "755th",
  "seventh hundred fiftie-sixth": "756th",
  "seventh hundred fiftie-seventh": "757th",
  "seventh hundred fiftie-eighth": "758th",
  "seventh hundred fiftie-ninth": "759th",
  "seventh hundred sixtieth": "760th",
  "seventh hundred sixtie-first": "761st",
  "seventh hundred sixtie-second": "762nd",
  "seventh hundred sixtie-third": "763rd",
  "seventh hundred sixtie-fourth": "764th",
  "seventh hundred sixtie-fifth": "765th",
  "seventh hundred sixtie-sixth": "766th",
  "seventh hundred sixtie-seventh": "767th",
  "seventh hundred sixtie-eighth": "768th",
  "seventh hundred sixtie-ninth": "769th",
  "seventh hundred seventieth": "770th",
  "seventh hundred seventie-first": "771st",
  "seventh hundred seventie-second": "772nd",
  "seventh hundred seventie-third": "773rd",
  "seventh hundred seventie-fourth": "774th",
  "seventh hundred seventie-fifth": "775th",
  "seventh hundred seventie-sixth": "776th",
  "seventh hundred seventie-seventh": "777th",
  "seventh hundred seventie-eighth": "778th",
  "seventh hundred seventie-ninth": "779th",
  "seventh hundred eightieth": "780th",
  "seventh hundred eightie-first": "781st",
  "seventh hundred eightie-second": "782nd",
  "seventh hundred eightie-third": "783rd",
  "seventh hundred eightie-fourth": "784th",
  "seventh hundred eightie-fifth": "785th",
  "seventh hundred eightie-sixth": "786th",
  "seventh hundred eightie-seventh": "787th",
  "seventh hundred eightie-eighth": "788th",
  "seventh hundred eightie-ninth": "789th",
  "seventh hundred ninetieth": "790th",
  "seventh hundred ninetie-first": "791st",
  "seventh hundred ninetie-second": "792nd",
  "seventh hundred ninetie-third": "793rd",
  "seventh hundred ninetie-fourth": "794th",
  "seventh hundred ninetie-fifth": "795th",
  "seventh hundred ninetie-sixth": "796th",
  "seventh hundred ninetie-seventh": "797th",
  "seventh hundred ninetie-eighth": "798th",
  "seventh hundred ninetie-ninth": "799th",
  "eighth hundredth": "800th",
  "eighth hundred first": "801st",
  "eighth hundred second": "802nd",
  "eighth hundred third": "803rd",
  "eighth hundred fourth": "804th",
  "eighth hundred fifth": "805th",
  "eighth hundred sixth": "806th",
  "eighth hundred seventh": "807th",
  "eighth hundred eighth": "808th",
  "eighth hundred ninth": "809th",
  "eighth hundred tenth": "810th",
  "eighth hundred eleventh": "811th",
  "eighth hundred twelfth": "812th",
  "eighth hundred thirteenth": "813th",
  "eighth hundred fourteenth": "814th",
  "eighth hundred fifteenth": "815th",
  "eighth hundred sixteenth": "816th",
  "eighth hundred seventeenth": "817th",
  "eighth hundred eighteenth": "818th",
  "eighth hundred nineteenth": "819th",
  "eighth hundred twentieth": "820th",
  "eighth hundred twentie-first": "821st",
  "eighth hundred twentie-second": "822nd",
  "eighth hundred twentie-third": "823rd",
  "eighth hundred twentie-fourth": "824th",
  "eighth hundred twentie-fifth": "825th",
  "eighth hundred twentie-sixth": "826th",
  "eighth hundred twentie-seventh": "827th",
  "eighth hundred twentie-eighth": "828th",
  "eighth hundred twentie-ninth": "829th",
  "eighth hundred thirtieth": "830th",
  "eighth hundred thirtie-first": "831st",
  "eighth hundred thirtie-second": "832nd",
  "eighth hundred thirtie-third": "833rd",
  "eighth hundred thirtie-fourth": "834th",
  "eighth hundred thirtie-fifth": "835th",
  "eighth hundred thirtie-sixth": "836th",
  "eighth hundred thirtie-seventh": "837th",
  "eighth hundred thirtie-eighth": "838th",
  "eighth hundred thirtie-ninth": "839th",
  "eighth hundred fortieth": "840th",
  "eighth hundred fortie-first": "841st",
  "eighth hundred fortie-second": "842nd",
  "eighth hundred fortie-third": "843rd",
  "eighth hundred fortie-fourth": "844th",
  "eighth hundred fortie-fifth": "845th",
  "eighth hundred fortie-sixth": "846th",
  "eighth hundred fortie-seventh": "847th",
  "eighth hundred fortie-eighth": "848th",
  "eighth hundred fortie-ninth": "849th",
  "eighth hundred fiftieth": "850th",
  "eighth hundred fiftie-first": "851st",
  "eighth hundred fiftie-second": "852nd",
  "eighth hundred fiftie-third": "853rd",
  "eighth hundred fiftie-fourth": "854th",
  "eighth hundred fiftie-fifth": "855th",
  "eighth hundred fiftie-sixth": "856th",
  "eighth hundred fiftie-seventh": "857th",
  "eighth hundred fiftie-eighth": "858th",
  "eighth hundred fiftie-ninth": "859th",
  "eighth hundred sixtieth": "860th",
  "eighth hundred sixtie-first": "861st",
  "eighth hundred sixtie-second": "862nd",
  "eighth hundred sixtie-third": "863rd",
  "eighth hundred sixtie-fourth": "864th",
  "eighth hundred sixtie-fifth": "865th",
  "eighth hundred sixtie-sixth": "866th",
  "eighth hundred sixtie-seventh": "867th",
  "eighth hundred sixtie-eighth": "868th",
  "eighth hundred sixtie-ninth": "869th",
  "eighth hundred seventieth": "870th",
  "eighth hundred seventie-first": "871st",
  "eighth hundred seventie-second": "872nd",
  "eighth hundred seventie-third": "873rd",
  "eighth hundred seventie-fourth": "874th",
  "eighth hundred seventie-fifth": "875th",
  "eighth hundred seventie-sixth": "876th",
  "eighth hundred seventie-seventh": "877th",
  "eighth hundred seventie-eighth": "878th",
  "eighth hundred seventie-ninth": "879th",
  "eighth hundred eightieth": "880th",
  "eighth hundred eightie-first": "881st",
  "eighth hundred eightie-second": "882nd",
  "eighth hundred eightie-third": "883rd",
  "eighth hundred eightie-fourth": "884th",
  "eighth hundred eightie-fifth": "885th",
  "eighth hundred eightie-sixth": "886th",
  "eighth hundred eightie-seventh": "887th",
  "eighth hundred eightie-eighth": "888th",
  "eighth hundred eightie-ninth": "889th",
  "eighth hundred ninetieth": "890th",
  "eighth hundred ninetie-first": "891st",
  "eighth hundred ninetie-second": "892nd",
  "eighth hundred ninetie-third": "893rd",
  "eighth hundred ninetie-fourth": "894th",
  "eighth hundred ninetie-fifth": "895th",
  "eighth hundred ninetie-sixth": "896th",
  "eighth hundred ninetie-seventh": "897th",
  "eighth hundred ninetie-eighth": "898th",
  "eighth hundred ninetie-ninth": "899th",
  "ninth hundredth": "900th",
  "ninth hundred first": "901st",
  "ninth hundred second": "902nd",
  "ninth hundred third": "903rd",
  "ninth hundred fourth": "904th",
  "ninth hundred fifth": "905th",
  "ninth hundred sixth": "906th",
  "ninth hundred seventh": "907th",
  "ninth hundred eighth": "908th",
  "ninth hundred ninth": "909th",
  "ninth hundred tenth": "910th",
  "ninth hundred eleventh": "911th",
  "ninth hundred twelfth": "912th",
  "ninth hundred thirteenth": "913th",
  "ninth hundred fourteenth": "914th",
  "ninth hundred fifteenth": "915th",
  "ninth hundred sixteenth": "916th",
  "ninth hundred seventeenth": "917th",
  "ninth hundred eighteenth": "918th",
  "ninth hundred nineteenth": "919th",
  "ninth hundred twentieth": "920th",
  "ninth hundred twentie-first": "921st",
  "ninth hundred twentie-second": "922nd",
  "ninth hundred twentie-third": "923rd",
  "ninth hundred twentie-fourth": "924th",
  "ninth hundred twentie-fifth": "925th",
  "ninth hundred twentie-sixth": "926th",
  "ninth hundred twentie-seventh": "927th",
  "ninth hundred twentie-eighth": "928th",
  "ninth hundred twentie-ninth": "929th",
  "ninth hundred thirtieth": "930th",
  "ninth hundred thirtie-first": "931st",
  "ninth hundred thirtie-second": "932nd",
  "ninth hundred thirtie-third": "933rd",
  "ninth hundred thirtie-fourth": "934th",
  "ninth hundred thirtie-fifth": "935th",
  "ninth hundred thirtie-sixth": "936th",
  "ninth hundred thirtie-seventh": "937th",
  "ninth hundred thirtie-eighth": "938th",
  "ninth hundred thirtie-ninth": "939th",
  "ninth hundred fortieth": "940th",
  "ninth hundred fortie-first": "941st",
  "ninth hundred fortie-second": "942nd",
  "ninth hundred fortie-third": "943rd",
  "ninth hundred fortie-fourth": "944th",
  "ninth hundred fortie-fifth": "945th",
  "ninth hundred fortie-sixth": "946th",
  "ninth hundred fortie-seventh": "947th",
  "ninth hundred fortie-eighth": "948th",
  "ninth hundred fortie-ninth": "949th",
  "ninth hundred fiftieth": "950th",
  "ninth hundred fiftie-first": "951st",
  "ninth hundred fiftie-second": "952nd",
  "ninth hundred fiftie-third": "953rd",
  "ninth hundred fiftie-fourth": "954th",
  "ninth hundred fiftie-fifth": "955th",
  "ninth hundred fiftie-sixth": "956th",
  "ninth hundred fiftie-seventh": "957th",
  "ninth hundred fiftie-eighth": "958th",
  "ninth hundred fiftie-ninth": "959th",
  "ninth hundred sixtieth": "960th",
  "ninth hundred sixtie-first": "961st",
  "ninth hundred sixtie-second": "962nd",
  "ninth hundred sixtie-third": "963rd",
  "ninth hundred sixtie-fourth": "964th",
  "ninth hundred sixtie-fifth": "965th",
  "ninth hundred sixtie-sixth": "966th",
  "ninth hundred sixtie-seventh": "967th",
  "ninth hundred sixtie-eighth": "968th",
  "ninth hundred sixtie-ninth": "969th",
  "ninth hundred seventieth": "970th",
  "ninth hundred seventie-first": "971st",
  "ninth hundred seventie-second": "972nd",
  "ninth hundred seventie-third": "973rd",
  "ninth hundred seventie-fourth": "974th",
  "ninth hundred seventie-fifth": "975th",
  "ninth hundred seventie-sixth": "976th",
  "ninth hundred seventie-seventh": "977th",
  "ninth hundred seventie-eighth": "978th",
  "ninth hundred seventie-ninth": "979th",
  "ninth hundred eightieth": "980th",
  "ninth hundred eightie-first": "981st",
  "ninth hundred eightie-second": "982nd",
  "ninth hundred eightie-third": "983rd",
  "ninth hundred eightie-fourth": "984th",
  "ninth hundred eightie-fifth": "985th",
  "ninth hundred eightie-sixth": "986th",
  "ninth hundred eightie-seventh": "987th",
  "ninth hundred eightie-eighth": "988th",
  "ninth hundred eightie-ninth": "989th",
  "ninth hundred ninetieth": "990th",
  "ninth hundred ninetie-first": "991st",
  "ninth hundred ninetie-second": "992nd",
  "ninth hundred ninetie-third": "993rd",
  "ninth hundred ninetie-fourth": "994th",
  "ninth hundred ninetie-fifth": "995th",
  "ninth hundred ninetie-sixth": "996th",
  "ninth hundred ninetie-seventh": "997th",
  "ninth hundred ninetie-eighth": "998th",
  "ninth hundred ninetie-ninth": "999th",
  "one thousandth": "1000th"
}